type User @table {
  username: String!
  email: String!
  passwordHash: String!
  displayName: String
  createdAt: Timestamp
  updatedAt: Timestamp
}

type Session @table {
  user: User!
  token: String!
  expiresAt: Timestamp!
  createdAt: Timestamp
}